spring.application.name=CF_DuelProject
spring.data.mongodb.database=cf_duel_db
spring.data.mongodb.uri=mongodb+srv://mrunmayik1220_db_user:PGt62ph3MdnaFOCh@cluster0.adpth4w.mongodb.net/?appName=Cluster0

spring.security.oauth2.client.registration.google.client-id=640292651667-9374mtiqvp1s3mck7f3mh4pfggd7re1c.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
spring.data.mongodb.auto-index-creation=true