spring.application.name=CF_DuelProject
spring.data.mongodb.uri=MONGO_URI

spring.security.oauth2.client.registration.google.client-id=YOUR_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_SECRET